### ISSUE TITLE
C64 EMU

### ISSUE THREAD

**Issue by MAMware** [MAMware/do#2]
A C64 VICE.js emu on a browser where you can upload your files. 
Co-created with Microsoft copilot

### HTML

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commodore 64 Emulator</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="screen"></div>
    <input type="text" id="filenameInput" placeholder="Enter C64 executable filename">
    <button id="loadFileButton">Load File</button>
    <script src="vice/library-vice.js"></script>
    <script src="script.js"></script>
</body>
</html>
```
### CSS (styles.css)
```css
body {
    background-color: #0000AA;
    color: #FFFFFF;
    font-family: 'C64', monospace;
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    transition: background-color 0.5s, color 0.5s;
}

#screen {
    width: 80%;
    max-width: 800px;
    padding: 20px;
    background-color: #0000AA;
    border: 2px solid #FFFFFF;
    box-sizing: border-box;
}

.blink {
    animation: blink 1s step-end infinite;
}

@keyframes blink {
    from, to {
        color: transparent;
    }
    50% {
        color: #FFFFFF;
    }
}
```

### JavaScript

JavaScript to handle the user input and load the specified C64 executable file. Also the background color changes via device movement for visual nostalgia for the loader

```javascript
document.addEventListener('DOMContentLoaded', () => {
    const screen = document.getElementById('screen');
    const filenameInput = document.getElementById('filenameInput');
    const loadFileButton = document.getElementById('loadFileButton');

    // Device orientation event listener
    window.addEventListener('deviceorientation', function(event) {
        var alpha = event.alpha;
        var beta = event.beta;
        var gamma = event.gamma;

        // Convert the alpha, beta, and gamma values to RGB values
        var red = Math.abs(Math.floor((alpha / 360) * 255));
        var green = Math.abs(Math.floor((beta / 180) * 255));
        var blue = Math.abs(Math.floor((gamma / 90) * 255));

        // Set the background color for the body
        var backgroundColor = `rgb(${red}, ${green}, ${blue})`;
        document.body.style.backgroundColor = backgroundColor;

        // Calculate the brightness to determine text color
        var brightness = (red * 299 + green * 587 + blue * 114) / 1000;
        var textColor = brightness > 123 ? 'rgb(32, 32, 32)' : 'rgb(255, 255, 255)';

        // Set the text color for the body
        document.body.style.color = textColor;
    });

    // Function to load and run C64 executable file
    function loadC64Executable(file) {
        fetch(file)
            .then(response => response.arrayBuffer())
            .then(buffer => {
                VICE.loadPRG(buffer, {
                    autostart: true,
                    run: true
                });
            })
            .catch(error => console.error('Error loading C64 executable file:', error));
    }

    // Event listener for the load button
    loadFileButton.addEventListener('click', () => {
        const filename = filenameInput.value;
        if (filename) {
            const filePath = `c64/${filename}`;
            loadC64Executable(filePath);
        } else {
            alert('Please enter a filename.');
        }
    });

    // Initialize VICE.js
    function initializeVICE() {
        VICE.start({
            element: document.getElementById('screen'),
            romPath: 'path/to/roms', // Path to the ROM files
            onReady: () => {
                console.log('VICE.js is ready');
            }
        });
    }

    // Start VICE.js
    initializeVICE();
});
```
