### ISSUE TITLE
SID Player

### ISSUE THREAD

**Issue by MAMware** [MAMware/do#3]
On a browser should give you a Commodore 64 Emulator VICE.js, SID player jsSID & a kind.ish 8 bit synth via device orientation.

Allows users to input "the" SID filename and load the corresponding file from your site

Lacks of testing and proper code revision, alpha stage.

Co-created with Microsoft copilot.

###  HTML

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commodore 64 Emulator</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="screen"></div>
    <input type="text" id="filenameInput" placeholder="Enter SID filename">
    <button id="loadFileButton">Load File</button>
    <script src="vice/library-vice.js"></script>
    <script src="script.js"></script>
</body>
</html>
```
### CSS (styles.css)
```css
body {
    background-color: #0000AA;
    color: #FFFFFF;
    font-family: 'C64', monospace;
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    transition: background-color 0.5s, color 0.5s;
}

#screen {
    width: 80%;
    max-width: 800px;
    padding: 20px;
    background-color: #0000AA;
    border: 2px solid #FFFFFF;
    box-sizing: border-box;
}

.blink {
    animation: blink 1s step-end infinite;
}

@keyframes blink {
    from, to {
        color: transparent;
    }
    50% {
        color: #FFFFFF;
    }
}
```

### JavaScript

```javascript
document.addEventListener('DOMContentLoaded', () => {
    const screen = document.getElementById('screen');
    const filenameInput = document.getElementById('filenameInput');
    const loadFileButton = document.getElementById('loadFileButton');

    // Create an Audio Context
    var audioContext = new (window.AudioContext || window.webkitAudioContext)();

    // Create Oscillator Nodes
    var oscillator1 = audioContext.createOscillator();
    var oscillator2 = audioContext.createOscillator();
    var oscillator3 = audioContext.createOscillator();

    // Set oscillator types (sine, square, sawtooth, triangle)
    oscillator1.type = 'square';
    oscillator2.type = 'sawtooth';
    oscillator3.type = 'triangle';

    // Create Gain Nodes for volume control
    var gainNode1 = audioContext.createGain();
    var gainNode2 = audioContext.createGain();
    var gainNode3 = audioContext.createGain();

    // Connect the oscillators to the gain nodes
    oscillator1.connect(gainNode1);
    oscillator2.connect(gainNode2);
    oscillator3.connect(gainNode3);

    // Connect the gain nodes to the destination (speakers)
    gainNode1.connect(audioContext.destination);
    gainNode2.connect(audioContext.destination);
    gainNode3.connect(audioContext.destination);

    // Start the oscillators
    oscillator1.start();
    oscillator2.start();
    oscillator3.start();

    // Device orientation event listener
    window.addEventListener('deviceorientation', function(event) {
        var alpha = event.alpha;
        var beta = event.beta;
        var gamma = event.gamma;

        // Convert the alpha, beta, and gamma values to RGB values
        var red = Math.abs(Math.floor((alpha / 360) * 255));
        var green = Math.abs(Math.floor((beta / 180) * 255));
        var blue = Math.abs(Math.floor((gamma / 90) * 255));

        // Set the background color for the body
        var backgroundColor = `rgb(${red}, ${green}, ${blue})`;
        document.body.style.backgroundColor = backgroundColor;

        // Calculate the brightness to determine text color
        var brightness = (red * 299 + green * 587 + blue * 114) / 1000;
        var textColor = brightness > 123 ? 'rgb(32, 32, 32)' : 'rgb(255, 255, 255)';

        // Set the text color for the body
        document.body.style.color = textColor;

        // Update the oscillator frequencies based on device orientation
        var baseFrequency = 80; // Base frequency in Hz
        var frequency1 = baseFrequency + (beta * 2); // Adjust the multiplier as needed
        var frequency2 = baseFrequency * 1.25 + (gamma * 2); // Major third
        var frequency3 = baseFrequency * 1.5 + (alpha * 2); // Perfect fifth

        oscillator1.frequency.setValueAtTime(frequency1, audioContext.currentTime);
        oscillator2.frequency.setValueAtTime(frequency2, audioContext.currentTime);
        oscillator3.frequency.setValueAtTime(frequency3, audioContext.currentTime);
    });

    // Function to load and play SID file
    function playSID(file) {
        const player = new jsSID();
        fetch(file)
            .then(response => response.arrayBuffer())
            .then(buffer => {
                player.load(buffer);
                player.play();
            })
            .catch(error => console.error('Error loading SID file:', error));
    }

    // Event listener for the load button
    loadFileButton.addEventListener('click', () => {
        const filename = filenameInput.value;
        if (filename) {
            const filePath = `sid/${filename}`;
            playSID(filePath);
        } else {
            alert('Please enter a filename.');
        }
    });

    // Initialize VICE.js
    function initializeVICE() {
        // Assuming VICE.js provides a global function to start the emulator
        VICE.start({
            element: document.getElementById('screen'),
            romPath: 'path/to/roms', // Path to the ROM files
            onReady: () => {
                console.log('VICE.js is ready');
            }
        });
    }

    // Start VICE.js
    initializeVICE();
});
```
